version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: openclip_dev
      POSTGRES_USER: openclip_dev
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openclip_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache for development
  redis-dev:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API for development
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=postgresql://openclip_dev:dev_password@postgres-dev:5432/openclip_dev
      - REDIS_HOST=redis-dev
      - SECRET_KEY=dev_secret_key_not_for_production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/temp:/app/temp
      - ./backend/outputs:/app/outputs
    ports:
      - "8001:8000"
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # Frontend development server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
      - VITE_ENVIRONMENT=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  default:
    driver: bridge 